services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parana-hogar
    restart: always
    ports:
      - "3011:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: parana-hogar-nginx
    ports:
      - "20001:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - nuxt-app
    restart: always
